"""Auto-generated SKiDL circuit: 1
============================================================
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

c_template = _make_template("C", "C", "capacitor", "Capacitor_SMD:C_0805_2012Metric", ['1', '2'])
i_template = _make_template("I", "I", "current source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])
q_template = _make_template("Q", "Q", "transistor (BJT)", "Package_TO_SOT_SMD:SOT-23", ['C', 'B', 'E'])
r_template = _make_template("R", "R", "resistor", "Resistor_SMD:R_0805_2012Metric", ['1', '2'])
v_template = _make_template("V", "V", "voltage source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])


# === Nets ===

net_VCC = Net("VCC")
net_VCC.netio = "i"
net_GND = Net("GND")
net_GND.do_erc = False
net_VEE = Net("VEE")
net_VEE.netio = "i"
net_IN = Net("IN")
net_IN.netio = "i"
net_OUT = Net("OUT")
net_OUT.netio = "o"
net_NFB = Net("NFB")
net_NIP = Net("NIP")
net_C1 = Net("C1")
net_TAIL = Net("TAIL")
net_C2 = Net("C2")
net_VAS_C = Net("VAS_C")
net_VAS_E = Net("VAS_E")
net_BDRV_P = Net("BDRV_P")
net_VBMULT = Net("VBMULT")
net_BDRV_N = Net("BDRV_N")
net_DRV_P = Net("DRV_P")
net_DRV_N = Net("DRV_N")
net_B9 = Net("B9")
net_B10 = Net("B10")
net_NZ = Net("NZ")


# === Components ===

VCC = v_template(value='+15')
VEE = v_template(value='-15')
VIN = v_template(value='1')
RF = r_template(value='22k')
RG = r_template(value='1k')
RIN = r_template(value='1k')
Q1 = q_template(value='QNPN')
Q2 = q_template(value='QNPN')
ITAIL = i_template(value='2mA')
Q3 = q_template(value='QPNP')
Q4 = q_template(value='QPNP')
RCM1 = r_template(value='100Meg')
RCM2 = r_template(value='100Meg')
Q5 = q_template(value='QNPN')
RE5 = r_template(value='220')
IVAS = i_template(value='6mA')
CCOMP = c_template(value='100p')
RC5 = r_template(value='4.7k')
Q6 = q_template(value='QNPN')
RB1 = r_template(value='2.2k')
RB2 = r_template(value='1k')
RBIAS = r_template(value='2.2k')
RBIAS2 = r_template(value='2.2k')
Q7 = q_template(value='QNPN')
Q8 = q_template(value='QPNP')
RDP = r_template(value='47')
RDN = r_template(value='47')
Q9 = q_template(value='QNPNPWR')
Q10 = q_template(value='QPNPPWR')
RE9 = r_template(value='0.22')
RE10 = r_template(value='0.22')
RL = r_template(value='8')
RZ = r_template(value='10')
CZ = c_template(value='100n')
RBI = r_template(value='100k')


# === Connections ===

VCC[1] += net_VCC
VCC[2] += net_GND
VEE[1] += net_VEE
VEE[2] += net_GND
VIN[1] += net_IN
VIN[2] += net_GND
RF[1] += net_OUT
RF[2] += net_NFB
RG[1] += net_NFB
RG[2] += net_GND
RIN[1] += net_IN
RIN[2] += net_NIP
Q1[1] += net_C1
Q1[2] += net_NIP
Q1[3] += net_TAIL
Q2[1] += net_C2
Q2[2] += net_NFB
Q2[3] += net_TAIL
ITAIL[1] += net_TAIL
ITAIL[2] += net_VEE
Q3[1] += net_C1
Q3[2] += net_C1
Q3[3] += net_VCC
Q4[1] += net_C2
Q4[2] += net_C1
Q4[3] += net_VCC
RCM1[1] += net_C1
RCM1[2] += net_GND
RCM2[1] += net_C2
RCM2[2] += net_GND
Q5[1] += net_VAS_C
Q5[2] += net_C2
Q5[3] += net_VAS_E
RE5[1] += net_VAS_E
RE5[2] += net_VEE
IVAS[1] += net_VAS_E
IVAS[2] += net_VEE
CCOMP[1] += net_VAS_C
CCOMP[2] += net_C2
RC5[1] += net_VCC
RC5[2] += net_VAS_C
Q6[1] += net_BDRV_P
Q6[2] += net_VBMULT
Q6[3] += net_BDRV_N
RB1[1] += net_BDRV_P
RB1[2] += net_VBMULT
RB2[1] += net_VBMULT
RB2[2] += net_BDRV_N
RBIAS[1] += net_VAS_C
RBIAS[2] += net_BDRV_P
RBIAS2[1] += net_BDRV_N
RBIAS2[2] += net_VEE
Q7[1] += net_VCC
Q7[2] += net_BDRV_P
Q7[3] += net_DRV_P
Q8[1] += net_VEE
Q8[2] += net_BDRV_N
Q8[3] += net_DRV_N
RDP[1] += net_DRV_P
RDP[2] += net_B9
RDN[1] += net_DRV_N
RDN[2] += net_B10
Q9[1] += net_VCC
Q9[2] += net_B9
Q9[3] += net_OUT
Q10[1] += net_VEE
Q10[2] += net_B10
Q10[3] += net_OUT
RE9[1] += net_OUT
RE9[2] += net_GND
RE10[1] += net_GND
RE10[2] += net_OUT
RL[1] += net_OUT
RL[2] += net_GND
RZ[1] += net_OUT
RZ[2] += net_NZ
CZ[1] += net_NZ
CZ[2] += net_GND
RBI[1] += net_NIP
RBI[2] += net_GND


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
