"""Auto-generated SKiDL circuit: 2
========================================================
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

i_template = _make_template("I", "I", "current source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])
m_template = _make_template("M", "M", "transistor (MOSFET)", "Package_TO_SOT_SMD:SOT-23", ['D', 'G', 'S', 'B'])
v_template = _make_template("V", "V", "voltage source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])


# === Nets ===

net_vdd = Net("vdd")
net_vdd.netio = "i"
net_GND = Net("GND")
net_GND.do_erc = False
net_inp = Net("inp")
net_inp.netio = "i"
net_inn = Net("inn")
net_inn.netio = "i"
net_tail = Net("tail")
net_outp = Net("outp")
net_outp.netio = "o"
net_outn = Net("outn")
net_outn.netio = "o"


# === Components ===

VDD = v_template(value='1.8')
VINP = v_template(value='0.9')
VINN = v_template(value='0.9')
ITAIL = i_template(value='20u')
M1 = m_template(value='NMOS')
M2 = m_template(value='NMOS')
M3 = m_template(value='PMOS')
M4 = m_template(value='PMOS')


# === Connections ===

VDD[1] += net_vdd
VDD[2] += net_GND
VINP[1] += net_inp
VINP[2] += net_GND
VINN[1] += net_inn
VINN[2] += net_GND
ITAIL[1] += net_tail
ITAIL[2] += net_GND
M1[1] += net_outp
M1[2] += net_inp
M1[3] += net_tail
M1[4] += net_GND
M2[1] += net_outn
M2[2] += net_inn
M2[3] += net_tail
M2[4] += net_GND
M3[1] += net_outp
M3[2] += net_outp
M3[3] += net_vdd
M3[4] += net_vdd
M4[1] += net_outn
M4[2] += net_outp
M4[3] += net_vdd
M4[4] += net_vdd


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
