"""Auto-generated SKiDL circuit: 3
============================================================
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

b_template = _make_template("B", "B", "component", "Package_DIP:DIP-8_W7.62mm", ['+', '-'])
c_template = _make_template("C", "C", "capacitor", "Capacitor_SMD:C_0805_2012Metric", ['1', '2'])
i_template = _make_template("I", "I", "current source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])
j_template = _make_template("J", "J", "transistor (JFET)", "Package_TO_SOT_SMD:SOT-23", ['D', 'G', 'S'])
l_template = _make_template("L", "L", "inductor", "Inductor_SMD:L_0805_2012Metric", ['1', '2'])
q_template = _make_template("Q", "Q", "transistor (BJT)", "Package_TO_SOT_SMD:SOT-23", ['C', 'B', 'E'])
r_template = _make_template("R", "R", "resistor", "Resistor_SMD:R_0805_2012Metric", ['1', '2'])
v_template = _make_template("V", "V", "voltage source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])
x_template = _make_template("X", "X", "subcircuit", "Package_DIP:DIP-8_W7.62mm", ['1', '2'])


# === Nets ===

net_VCC = Net("VCC")
net_VCC.netio = "i"
net_GND = Net("GND")
net_GND.do_erc = False
net_VEE = Net("VEE")
net_VEE.netio = "i"
net_IN = Net("IN")
net_IN.netio = "i"
net_NIN = Net("NIN")
net_NIN.netio = "i"
net_OUT = Net("OUT")
net_OUT.netio = "o"
net_FB = Net("FB")
net_ND1 = Net("ND1")
net_NTAIL = Net("NTAIL")
net_ND2 = Net("ND2")
net_ND2.do_erc = False
net_NERR = Net("NERR")
net_NSRV = Net("NSRV")
net_VAS = Net("VAS")
net_NBIAS = Net("NBIAS")
net_NBIAS.do_erc = False
net_BUP = Net("BUP")
net_BDN = Net("BDN")
net_DRVUP = Net("DRVUP")
net_DRVDN = Net("DRVDN")
net_BPU1 = Net("BPU1")
net_EPU1 = Net("EPU1")
net_BPU2 = Net("BPU2")
net_EPU2 = Net("EPU2")
net_BPU3 = Net("BPU3")
net_EPU3 = Net("EPU3")
net_BPU4 = Net("BPU4")
net_EPU4 = Net("EPU4")
net_BPD1 = Net("BPD1")
net_EPD1 = Net("EPD1")
net_BPD2 = Net("BPD2")
net_EPD2 = Net("EPD2")
net_BPD3 = Net("BPD3")
net_EPD3 = Net("EPD3")
net_BPD4 = Net("BPD4")
net_EPD4 = Net("EPD4")
net_SPK = Net("SPK")
net_NZ = Net("NZ")


# === Components ===

VCC = v_template(value='90')
VEE = v_template(value='-90')
CDEC_P = c_template(value='2200u')
CDEC_N = c_template(value='2200u')
VIN = v_template(value='1')
RIN = r_template(value='2k')
CINRF = c_template(value='100p')
RINB = r_template(value='270k')
RFB = r_template(value='22k')
RFBG = r_template(value='1k')
JINP = j_template(value='NJF_IN')
JINN = j_template(value='NJF_IN')
ITAIL = i_template(value='8m')
QML1 = q_template(value='PNP_SMALL')
QML2 = q_template(value='PNP_SMALL')
RERR = r_template(value='100k')
XSERVO = x_template(value='OPAMP_SIMPLE')
RSRV = r_template(value='330k')
CSRV = c_template(value='2.2u')
QVAS = q_template(value='NPN_VAS')
IVAS = i_template(value='10m')
CCOMP = c_template(value='100p')
RSTOP = r_template(value='100')
BUPSRC = b_template(value='V = { V(VAS) + 1.25 }')
BDNSRC = b_template(value='V = { V(VAS) - 1.25 }')
QDRVU = q_template(value='NPN_DRV')
QDRVD = q_template(value='PNP_DRV')
RBPU1 = r_template(value='100')
QOP1 = q_template(value='NPN_PWR')
REOP1 = r_template(value='0.47')
RBPU2 = r_template(value='100')
QOP2 = q_template(value='NPN_PWR')
REOP2 = r_template(value='0.47')
RBPU3 = r_template(value='100')
QOP3 = q_template(value='NPN_PWR')
REOP3 = r_template(value='0.47')
RBPU4 = r_template(value='100')
QOP4 = q_template(value='NPN_PWR')
REOP4 = r_template(value='0.47')
RBPD1 = r_template(value='100')
QON1 = q_template(value='PNP_PWR')
REON1 = r_template(value='0.47')
RBPD2 = r_template(value='100')
QON2 = q_template(value='PNP_PWR')
REON2 = r_template(value='0.47')
RBPD3 = r_template(value='100')
QON3 = q_template(value='PNP_PWR')
REON3 = r_template(value='0.47')
RBPD4 = r_template(value='100')
QON4 = q_template(value='PNP_PWR')
REON4 = r_template(value='0.47')
LOUT = l_template(value='1.5u')
RLOUT = r_template(value='10')
RZOB = r_template(value='10')
CZOB = c_template(value='0.022u')
RL = r_template(value='8')


# === Connections ===

VCC[1] += net_VCC
VCC[2] += net_GND
VEE[1] += net_VEE
VEE[2] += net_GND
CDEC_P[1] += net_VCC
CDEC_P[2] += net_GND
CDEC_N[1] += net_VEE
CDEC_N[2] += net_GND
VIN[1] += net_IN
VIN[2] += net_GND
RIN[1] += net_IN
RIN[2] += net_NIN
CINRF[1] += net_NIN
CINRF[2] += net_GND
RINB[1] += net_NIN
RINB[2] += net_GND
RFB[1] += net_OUT
RFB[2] += net_FB
RFBG[1] += net_FB
RFBG[2] += net_GND
JINP[1] += net_ND1
JINP[2] += net_NIN
JINP[3] += net_NTAIL
JINN[1] += net_ND2
JINN[2] += net_FB
JINN[3] += net_NTAIL
ITAIL[1] += net_NTAIL
ITAIL[2] += net_VEE
QML1[1] += net_ND1
QML1[2] += net_ND1
QML1[3] += net_VCC
QML2[1] += net_NERR
QML2[2] += net_ND1
QML2[3] += net_VCC
RERR[1] += net_NERR
RERR[2] += net_GND
XSERVO[1] += net_GND
XSERVO[2] += net_OUT
XSERVO[3] += net_NSRV
XSERVO[4] += net_VCC
XSERVO[5] += net_VEE
RSRV[1] += net_NSRV
RSRV[2] += net_FB
CSRV[1] += net_NSRV
CSRV[2] += net_OUT
QVAS[1] += net_VAS
QVAS[2] += net_NERR
QVAS[3] += net_VEE
IVAS[1] += net_VCC
IVAS[2] += net_VAS
CCOMP[1] += net_VAS
CCOMP[2] += net_NERR
RSTOP[1] += net_VAS
RSTOP[2] += net_NBIAS
BUPSRC[1] += net_BUP
BUPSRC[2] += net_GND
BDNSRC[1] += net_BDN
BDNSRC[2] += net_GND
QDRVU[1] += net_VCC
QDRVU[2] += net_BUP
QDRVU[3] += net_DRVUP
QDRVD[1] += net_VEE
QDRVD[2] += net_BDN
QDRVD[3] += net_DRVDN
RBPU1[1] += net_DRVUP
RBPU1[2] += net_BPU1
QOP1[1] += net_VCC
QOP1[2] += net_BPU1
QOP1[3] += net_EPU1
REOP1[1] += net_EPU1
REOP1[2] += net_OUT
RBPU2[1] += net_DRVUP
RBPU2[2] += net_BPU2
QOP2[1] += net_VCC
QOP2[2] += net_BPU2
QOP2[3] += net_EPU2
REOP2[1] += net_EPU2
REOP2[2] += net_OUT
RBPU3[1] += net_DRVUP
RBPU3[2] += net_BPU3
QOP3[1] += net_VCC
QOP3[2] += net_BPU3
QOP3[3] += net_EPU3
REOP3[1] += net_EPU3
REOP3[2] += net_OUT
RBPU4[1] += net_DRVUP
RBPU4[2] += net_BPU4
QOP4[1] += net_VCC
QOP4[2] += net_BPU4
QOP4[3] += net_EPU4
REOP4[1] += net_EPU4
REOP4[2] += net_OUT
RBPD1[1] += net_DRVDN
RBPD1[2] += net_BPD1
QON1[1] += net_VEE
QON1[2] += net_BPD1
QON1[3] += net_EPD1
REON1[1] += net_EPD1
REON1[2] += net_OUT
RBPD2[1] += net_DRVDN
RBPD2[2] += net_BPD2
QON2[1] += net_VEE
QON2[2] += net_BPD2
QON2[3] += net_EPD2
REON2[1] += net_EPD2
REON2[2] += net_OUT
RBPD3[1] += net_DRVDN
RBPD3[2] += net_BPD3
QON3[1] += net_VEE
QON3[2] += net_BPD3
QON3[3] += net_EPD3
REON3[1] += net_EPD3
REON3[2] += net_OUT
RBPD4[1] += net_DRVDN
RBPD4[2] += net_BPD4
QON4[1] += net_VEE
QON4[2] += net_BPD4
QON4[3] += net_EPD4
REON4[1] += net_EPD4
REON4[2] += net_OUT
LOUT[1] += net_OUT
LOUT[2] += net_SPK
RLOUT[1] += net_OUT
RLOUT[2] += net_SPK
RZOB[1] += net_OUT
RZOB[2] += net_NZ
CZOB[1] += net_NZ
CZOB[2] += net_GND
RL[1] += net_SPK
RL[2] += net_GND


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
