"""Auto-generated SKiDL circuit: 4
========================================================
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

c_template = _make_template("C", "C", "capacitor", "Capacitor_SMD:C_0805_2012Metric", ['1', '2'])
r_template = _make_template("R", "R", "resistor", "Resistor_SMD:R_0805_2012Metric", ['1', '2'])
v_template = _make_template("V", "V", "voltage source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])
x_template = _make_template("X", "X", "subcircuit", "Package_DIP:DIP-8_W7.62mm", ['1', '2'])


# === Nets ===

net_VDD = Net("VDD")
net_VDD.netio = "i"
net_GND = Net("GND")
net_GND.do_erc = False
net_REF = Net("REF")
net_VBIAS = Net("VBIAS")
net_VCTRL = Net("VCTRL")
net_FBK = Net("FBK")
net_TAP1 = Net("TAP1")
net_TAP2 = Net("TAP2")
net_TAP3 = Net("TAP3")
net_TAP4 = Net("TAP4")
net_TAP5 = Net("TAP5")
net_TAP6 = Net("TAP6")
net_TAP7 = Net("TAP7")


# === Components ===

VDD = v_template(value='{VDDVAL}')
VREF = v_template(value='PULSE(0 {VDDVAL} 0 50p 50p {TCLK/2} {TCLK})')
VBIAS = v_template(value='{VCM}')
RBIAS = r_template(value='200k')
CCTRL = c_template(value='300p')
RLEAK = r_template(value='2Meg')
XPFD = x_template(value='PFD_CP_ABS')
XDL1 = x_template(value='DLL_STAGE')
XDL2 = x_template(value='DLL_STAGE')
XDL3 = x_template(value='DLL_STAGE')
XDL4 = x_template(value='DLL_STAGE')
XDL5 = x_template(value='DLL_STAGE')
XDL6 = x_template(value='DLL_STAGE')
XDL7 = x_template(value='DLL_STAGE')
XDL8 = x_template(value='DLL_STAGE')
CT1 = c_template(value='10f')
CT2 = c_template(value='10f')
CT3 = c_template(value='10f')
CT4 = c_template(value='10f')
CT5 = c_template(value='10f')
CT6 = c_template(value='10f')
CT7 = c_template(value='10f')
CT8 = c_template(value='10f')


# === Connections ===

VDD[1] += net_VDD
VDD[2] += net_GND
VREF[1] += net_REF
VREF[2] += net_GND
VBIAS[1] += net_VBIAS
VBIAS[2] += net_GND
RBIAS[1] += net_VCTRL
RBIAS[2] += net_VBIAS
CCTRL[1] += net_VCTRL
CCTRL[2] += net_GND
RLEAK[1] += net_VCTRL
RLEAK[2] += net_GND
XPFD[1] += net_REF
XPFD[2] += net_FBK
XPFD[3] += net_VCTRL
XPFD[4] += net_VDD
XPFD[5] += net_GND
XDL1[1] += net_REF
XDL1[2] += net_TAP1
XDL1[3] += net_VCTRL
XDL1[4] += net_VDD
XDL1[5] += net_GND
XDL2[1] += net_TAP1
XDL2[2] += net_TAP2
XDL2[3] += net_VCTRL
XDL2[4] += net_VDD
XDL2[5] += net_GND
XDL3[1] += net_TAP2
XDL3[2] += net_TAP3
XDL3[3] += net_VCTRL
XDL3[4] += net_VDD
XDL3[5] += net_GND
XDL4[1] += net_TAP3
XDL4[2] += net_TAP4
XDL4[3] += net_VCTRL
XDL4[4] += net_VDD
XDL4[5] += net_GND
XDL5[1] += net_TAP4
XDL5[2] += net_TAP5
XDL5[3] += net_VCTRL
XDL5[4] += net_VDD
XDL5[5] += net_GND
XDL6[1] += net_TAP5
XDL6[2] += net_TAP6
XDL6[3] += net_VCTRL
XDL6[4] += net_VDD
XDL6[5] += net_GND
XDL7[1] += net_TAP6
XDL7[2] += net_TAP7
XDL7[3] += net_VCTRL
XDL7[4] += net_VDD
XDL7[5] += net_GND
XDL8[1] += net_TAP7
XDL8[2] += net_FBK
XDL8[3] += net_VCTRL
XDL8[4] += net_VDD
XDL8[5] += net_GND
CT1[1] += net_TAP1
CT1[2] += net_GND
CT2[1] += net_TAP2
CT2[2] += net_GND
CT3[1] += net_TAP3
CT3[2] += net_GND
CT4[1] += net_TAP4
CT4[2] += net_GND
CT5[1] += net_TAP5
CT5[2] += net_GND
CT6[1] += net_TAP6
CT6[2] += net_GND
CT7[1] += net_TAP7
CT7[2] += net_GND
CT8[1] += net_FBK
CT8[2] += net_GND


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
