"""Auto-generated SKiDL circuit: 5
============================================================
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

c_template = _make_template("C", "C", "capacitor", "Capacitor_SMD:C_0805_2012Metric", ['1', '2'])
i_template = _make_template("I", "I", "current source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])
q_template = _make_template("Q", "Q", "transistor (BJT)", "Package_TO_SOT_SMD:SOT-23", ['C', 'B', 'E'])
r_template = _make_template("R", "R", "resistor", "Resistor_SMD:R_0805_2012Metric", ['1', '2'])
v_template = _make_template("V", "V", "voltage source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])


# === Nets ===

net_VCC = Net("VCC")
net_VCC.netio = "i"
net_GND = Net("GND")
net_GND.do_erc = False
net_VEE = Net("VEE")
net_VEE.netio = "i"
net_IN1P = Net("IN1P")
net_IN1P.netio = "i"
net_IN1N = Net("IN1N")
net_IN1N.netio = "i"
net_IN2P = Net("IN2P")
net_IN2P.netio = "i"
net_IN2N = Net("IN2N")
net_IN2N.netio = "i"
net_TAIL1 = Net("TAIL1")
net_C1P = Net("C1P")
net_C1N = Net("C1N")
net_TAIL2 = Net("TAIL2")
net_C2P = Net("C2P")
net_C2N = Net("C2N")
net_EVAS1 = Net("EVAS1")
net_BUP = Net("BUP")
net_EVAS2 = Net("EVAS2")
net_BDN = Net("BDN")
net_NB = Net("NB")
net_NDRVU = Net("NDRVU")
net_NDRVL = Net("NDRVL")
net_BOUTU = Net("BOUTU")
net_BOUTU.netio = "o"
net_BOUTL = Net("BOUTL")
net_BOUTL.netio = "o"
net_EOUTU = Net("EOUTU")
net_EOUTU.netio = "o"
net_EOUTL = Net("EOUTL")
net_EOUTL.netio = "o"
net_OUT = Net("OUT")
net_OUT.netio = "o"
net_NZ = Net("NZ")


# === Components ===

VCC = v_template(value='35')
VEE = v_template(value='-35')
VIN1P = v_template(value='0')
VIN1N = v_template(value='0')
VIN2P = v_template(value='0')
VIN2N = v_template(value='0')
ITAIL1 = i_template(value='2m')
Q1 = q_template(value='NPN_IN')
Q2 = q_template(value='NPN_IN')
RC1P = r_template(value='10k')
RC1N = r_template(value='10k')
ITAIL2 = i_template(value='2m')
Q3 = q_template(value='PNP_IN')
Q4 = q_template(value='PNP_IN')
RC2P = r_template(value='10k')
RC2N = r_template(value='10k')
REVAS1 = r_template(value='2.2k')
QVAS1 = q_template(value='PNP_VAS')
ICVAS1 = i_template(value='4m')
CDOM1 = c_template(value='47p')
REVAS2 = r_template(value='2.2k')
QVAS2 = q_template(value='NPN_VAS')
ICVAS2 = i_template(value='4m')
CDOM2 = c_template(value='47p')
QBIAS = q_template(value='NPN_BIAS')
RB1 = r_template(value='2.7k')
RB2 = r_template(value='1.0k')
CBIAS = c_template(value='100p')
QDRVU = q_template(value='NPN_DRV')
QDRVL = q_template(value='PNP_DRV')
RBDU = r_template(value='47')
RBDL = r_template(value='47')
QOUTU = q_template(value='NPN_OUT')
QOUTL = q_template(value='PNP_OUT')
REU = r_template(value='0.22')
REL = r_template(value='0.22')
RLOAD = r_template(value='8')
CZOB = c_template(value='100n')
RZOB = r_template(value='10')
RLEAK1 = r_template(value='1Meg')
RLEAK2 = r_template(value='1Meg')
RLEAK3 = r_template(value='1Meg')


# === Connections ===

VCC[1] += net_VCC
VCC[2] += net_GND
VEE[1] += net_VEE
VEE[2] += net_GND
VIN1P[1] += net_IN1P
VIN1P[2] += net_GND
VIN1N[1] += net_IN1N
VIN1N[2] += net_GND
VIN2P[1] += net_IN2P
VIN2P[2] += net_GND
VIN2N[1] += net_IN2N
VIN2N[2] += net_GND
ITAIL1[1] += net_TAIL1
ITAIL1[2] += net_VEE
Q1[1] += net_C1P
Q1[2] += net_IN1P
Q1[3] += net_TAIL1
Q2[1] += net_C1N
Q2[2] += net_IN1N
Q2[3] += net_TAIL1
RC1P[1] += net_VCC
RC1P[2] += net_C1P
RC1N[1] += net_VCC
RC1N[2] += net_C1N
ITAIL2[1] += net_VCC
ITAIL2[2] += net_TAIL2
Q3[1] += net_C2P
Q3[2] += net_IN2P
Q3[3] += net_TAIL2
Q4[1] += net_C2N
Q4[2] += net_IN2N
Q4[3] += net_TAIL2
RC2P[1] += net_C2P
RC2P[2] += net_VEE
RC2N[1] += net_C2N
RC2N[2] += net_VEE
REVAS1[1] += net_VCC
REVAS1[2] += net_EVAS1
QVAS1[1] += net_BUP
QVAS1[2] += net_C1N
QVAS1[3] += net_EVAS1
ICVAS1[1] += net_BUP
ICVAS1[2] += net_VEE
CDOM1[1] += net_BUP
CDOM1[2] += net_C1N
REVAS2[1] += net_EVAS2
REVAS2[2] += net_VEE
QVAS2[1] += net_BDN
QVAS2[2] += net_C2N
QVAS2[3] += net_EVAS2
ICVAS2[1] += net_VCC
ICVAS2[2] += net_BDN
CDOM2[1] += net_BDN
CDOM2[2] += net_C2N
QBIAS[1] += net_BUP
QBIAS[2] += net_NB
QBIAS[3] += net_BDN
RB1[1] += net_BUP
RB1[2] += net_NB
RB2[1] += net_NB
RB2[2] += net_BDN
CBIAS[1] += net_BUP
CBIAS[2] += net_BDN
QDRVU[1] += net_VCC
QDRVU[2] += net_BUP
QDRVU[3] += net_NDRVU
QDRVL[1] += net_VEE
QDRVL[2] += net_BDN
QDRVL[3] += net_NDRVL
RBDU[1] += net_NDRVU
RBDU[2] += net_BOUTU
RBDL[1] += net_NDRVL
RBDL[2] += net_BOUTL
QOUTU[1] += net_VCC
QOUTU[2] += net_BOUTU
QOUTU[3] += net_EOUTU
QOUTL[1] += net_VEE
QOUTL[2] += net_BOUTL
QOUTL[3] += net_EOUTL
REU[1] += net_EOUTU
REU[2] += net_OUT
REL[1] += net_EOUTL
REL[2] += net_OUT
RLOAD[1] += net_OUT
RLOAD[2] += net_GND
CZOB[1] += net_NZ
CZOB[2] += net_GND
RZOB[1] += net_OUT
RZOB[2] += net_NZ
RLEAK1[1] += net_BUP
RLEAK1[2] += net_GND
RLEAK2[1] += net_BDN
RLEAK2[2] += net_GND
RLEAK3[1] += net_OUT
RLEAK3[2] += net_GND


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
