"""Auto-generated SKiDL circuit: cmos_inverter
CMOS Inverter
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

m_template = _make_template("M", "M", "transistor (MOSFET)", "Package_TO_SOT_SMD:SOT-23", ['D', 'G', 'S', 'B'])
v_template = _make_template("V", "V", "voltage source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])


# === Nets ===

net_VDD = Net("VDD")
net_VDD.netio = "i"
net_GND = Net("GND")
net_GND.do_erc = False
net_VOUT = Net("VOUT")
net_VOUT.netio = "o"
net_VIN = Net("VIN")
net_VIN.netio = "i"


# === Components ===

VDD = v_template(value='5')
M1 = m_template(value='PMOD')
M2 = m_template(value='NMOD')


# === Connections ===

VDD[1] += net_VDD
VDD[2] += net_GND
M1[1] += net_VOUT
M1[2] += net_VIN
M1[3] += net_VDD
M1[4] += net_VDD
M2[1] += net_VOUT
M2[2] += net_VIN
M2[3] += net_GND
M2[4] += net_GND


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
