"""Auto-generated SKiDL circuit: common_emitter_amp
Common Emitter Amplifier
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

q_template = _make_template("Q", "Q", "transistor (BJT)", "Package_TO_SOT_SMD:SOT-23", ['C', 'B', 'E'])
r_template = _make_template("R", "R", "resistor", "Resistor_SMD:R_0805_2012Metric", ['1', '2'])
v_template = _make_template("V", "V", "voltage source", "TestPoint:TestPoint_Pad_D1.0mm", ['+', '-'])


# === Nets ===

net_VCC = Net("VCC")
net_VCC.netio = "i"
net_GND = Net("GND")
net_GND.do_erc = False
net_VIN = Net("VIN")
net_VIN.netio = "i"
net_VIN.do_erc = False
net_BASE = Net("BASE")
net_VOUT = Net("VOUT")
net_VOUT.netio = "o"
net_EMITTER = Net("EMITTER")


# === Components ===

VCC = v_template(value='12')
RB = r_template(value='100k')
RC = r_template(value='4.7k')
RE = r_template(value='1k')
Q1 = q_template(value='2N2222')


# === Connections ===

VCC[1] += net_VCC
VCC[2] += net_GND
RB[1] += net_VIN
RB[2] += net_BASE
RC[1] += net_VCC
RC[2] += net_VOUT
RE[1] += net_EMITTER
RE[2] += net_GND
Q1[1] += net_VOUT
Q1[2] += net_BASE
Q1[3] += net_EMITTER


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
