"""Auto-generated SKiDL circuit: voltage_divider
Voltage Divider
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg


def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part


# === Part Templates ===

r_template = _make_template("R", "R", "resistor", "Resistor_SMD:R_0805_2012Metric", ['1', '2'])


# === Nets ===

net_VIN = Net("VIN")
net_VIN.netio = "i"
net_VIN.do_erc = False
net_VOUT = Net("VOUT")
net_VOUT.netio = "o"
net_GND = Net("GND")
net_GND.do_erc = False


# === Components ===

R1 = r_template(value='10k')
R2 = r_template(value='10k')


# === Connections ===

R1[1] += net_VIN
R1[2] += net_VOUT
R2[1] += net_VOUT
R2[2] += net_GND


# === Generate Output ===
ERC()
generate_netlist()
try:
    generate_svg()
    print("SVG schematic generated successfully.")
except Exception as exc:
    print(f"SVG generation failed: {exc}")
