"""SKiDL 代码模板与片段。"""

from __future__ import annotations

from ..models import Component, PIN_DEFS
from .footprint_map import get_footprint, get_description

# ---- 文件头 ----

HEADER_TEMPLATE = '''\
"""Auto-generated SKiDL circuit: {name}
{title}
Generated by spice2svg
"""

from skidl import ERC, Net, Part, Pin, SKIDL, TEMPLATE, generate_netlist, generate_svg
'''

# ---- 辅助函数 ----

TEMPLATE_FUNC = '''\

def _make_template(name: str, ref_prefix: str, description: str,
                   footprint: str, pin_names: list[str]) -> Part:
    """创建 SKiDL Part 模板。"""
    part = Part(name=name, tool=SKIDL, dest=TEMPLATE)
    part.ref_prefix = ref_prefix
    part.description = description
    part.keywords = description
    part.footprint = footprint
    for i, pname in enumerate(pin_names, start=1):
        part += Pin(num=i, name=pname, func=Pin.funcs.PASSIVE)
    return part
'''

# ---- 代码生成函数 ----

def safe_name(name: str) -> str:
    """将网络名转为合法 Python 标识符。"""
    s = name.replace("+", "_PLUS").replace("-", "_MINUS")
    s = s.replace("!", "").replace(".", "_")
    if s and s[0].isdigit():
        s = "_" + s
    return s


def generate_part_template(comp_type: str,
                           custom_footprint: str | None = None) -> str:
    pin_names = PIN_DEFS.get(comp_type, ["1", "2"])
    footprint = custom_footprint or get_footprint(comp_type)
    description = get_description(comp_type)
    return (
        f'{comp_type.lower()}_template = _make_template('
        f'"{comp_type}", "{comp_type}", "{description}", '
        f'"{footprint}", {pin_names!r})'
    )


def generate_net_declaration(net_name: str, direction: str = "inout",
                             is_ground: bool = False,
                             is_boundary: bool = False) -> str:
    sn = safe_name(net_name)
    lines = [f'net_{sn} = Net("{net_name}")']
    if direction == "input":
        lines.append(f'net_{sn}.netio = "i"')
    elif direction == "output":
        lines.append(f'net_{sn}.netio = "o"')
    if is_ground or is_boundary:
        lines.append(f'net_{sn}.do_erc = False')
    return "\n".join(lines)


def generate_component_instance(comp: Component) -> str:
    template_var = f"{comp.type.lower()}_template"
    safe_ref = comp.ref.replace(" ", "_")
    return f'{safe_ref} = {template_var}(value={comp.value!r})'


def generate_pin_connection(comp_ref: str, pin_num: int, net_name: str) -> str:
    safe_ref = comp_ref.replace(" ", "_")
    return f'{safe_ref}[{pin_num}] += net_{safe_name(net_name)}'
